version: "3"
services:
  app:
    container_name: app-server
    image: nextcloud:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
      - "443"
      - "9000"
    networks:
      - onlyoffice
    volumes:
      - app_data:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - onlyoffice
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password1234
    env_file:
      - db.env

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - "80"
      - "443"
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  caddy:
    container_name: caddy-server
    image: abiosoft/caddy:no-stats
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    environment:
      - CADDYPATH=/certs
      - ACME_AGREE=true
      # CHANGE THESE OR THE CONTAINER WILL FAIL TO RUN
      - CADDY_LETSENCRYPT_EMAIL=certificates@example.com
      - CADDY_EXTERNAL_DOMAIN=mydomain.com
      - CADDY_PROXY_URL=http://app:80
    volumes:
      - ./data/letsencrypt:/certs:rw
      - ./Caddyfile:/etc/Caddyfile:ro
      - app_data:/var/www/html

networks:
  onlyoffice:
    driver: "bridge"

    volumes:
  document_data:
  document_log:
  app_data:
  db:
  mysql_data:
